project:
    type: website
    output-dir: docs

website:
    title: "TAIH Symposium 2026"
    site-url: "https://uofc-taih.github.io/symposium-2026/"
    description: "First TAIH Symposium at the University of Calgary"
    navbar:
        background: primary
        left:
            - text: "Schedule"
              file: schedule.qmd
            - text: "Call for Papers"
              file: cfp.qmd
            - text: "Sponsors"
              file: sponsors.qmd
        right:
            - text: "Submit on OpenReview"
              href: "https://openreview.net/group?id=TAIH/2026/Symposium"
              target: _blank

format:
    html:
        theme: flatly
        css: styles.css
        toc: false
