---
title: "Call for Papers"
---

We invite submissions for the **TAIH Symposium 2026**. We welcome contributions from researchers and practitioners across academia and industry who are exploring the intersection of artificial intelligence and domain-specific challenges.

## Important Dates

* <span style="color: #777">**Submission deadline:** May 10, 2026, 11:59 PM MDT</span> (Submissions are now closed)
* **Author notification:** May 17, 2026, 11:59 PM MDT
* **Camera-ready deadline:** May 22, 2026, 11:59 PM MDT
* **Symposium date:** May 26, 2026, see [schedule](schedule.qmd) for details


## Topics of Interest

We welcome a broad spectrum of research on transdisciplinary efforts in development and use of AI. Examples are:

* AI in healthcare and medicine
* AI in critical infrastructure and energy
* Human-AI interaction and collaboration
* Ethical, governance, and societal implications of AI
* Transdisciplinary case studies and real-world applications
* Trustworthy ML foundations (explainability, interpretability, fairness, robustness, etc.)

## Submission Guidelines

We use a flexible, one-page format to make joining the conversation easy for all researchers.

### What to Submit

* **Length:** 1 page, plus references.
* **Format:** Flexible. You may submit an extended abstract, preliminary results, or a summary of recently published or previously presented work.
* **Template:** Standard single-column or double-column academic format (e.g., IEEE, ACM, or standard LaTeX article). PDF format is required.
* **Review Process:** All submissions will be peer-reviewed in a **double-blind process**. Please ensure your submitted PDF does not contain author names or affiliations.

### Presentation Format
Upon acceptance, authors will be invited to present their research at the symposium.

* We will have lightning talks for each accepted works (5-15min, depending on the number of accepted submissions). Participants with accepted work are asked to prepare presentation slides to reflect the core concepts of the submitted abstract---authors are encouraged to include any additional details, figures, and updates from the abstract submission.
* **Top Submissions:** The top three authors based on the peer review will receive rewards, sponsored by the Graduate College.

::: {.text-center style="margin-top: 40px;"}
[Submissions Closed](https://openreview.net/group?id=TAIH/2026/Symposium){.btn .btn-secondary .btn-lg role="button" aria-disabled="true"}
:::
